<?php

/**
 * @file
 * Contains localgov_search_solr.install.
 */

use Drupal\search_api\Entity\Index;
use Drupal\search_api\Entity\Server;

/**
 * Implements hook_install().
 */
function localgov_search_solr_install() {
  if (
    ($index = Index::load('localgov_sitewide_search')) &&
    ($index->getServerId() == '')
  ) {
    $server = Server::load('localgov_sitewide_solr');
    $index->setServer($server);
    $index->setStatus(TRUE);
    $index->save();
  }
}
